server {
    listen 80;
    server_name web.wazzifni.online;

    root /usr/share/nginx/html;
    index index.html;

    # Support for the root application
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Specific support for the course application
    location /course/ {
        alias /usr/share/nginx/html/course/;
        index index.html;
        try_files $uri $uri/ /course/index.html;
    }

    location /api-proxy/ {
        proxy_pass https://admin.wazzifni.online/api/;
        proxy_set_header Host api.wazzifni.net;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
